name: MiningLevelSystem
main: Deceitya\MiningLevel\MiningLevelSystem
version: 1.0.0
api: 4.0.0

load: POSTWORLD
author: deceitya
description: 採掘レベルシステム
website: https://github.com/deceitya/MiningLevelSystem

commands:
 milevel:
  description: MiningLevelSystemのコマンド
  usage: "/milevel <status>"
  permission: mining.command.milevel
permissions:
 mining.command.milevel:
  description: "Allows the user to run the milevel command"
  default: true
